server:
  port: 8003
eureka:
  instance:
    # 实例名字
    instance-id: stream-consumer8003
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
spring:
  application:
    name: stream-consumer
  rabbitmq:
    port: 5672
    host: 192.168.8.129
    username: guest
    password: guest
  cloud:
#    function:
#      definition: myBroadcast;myGroup
    stream:
      bindings:
        # 广播消息
        myBroadcast-in-0: # 消费者绑定名称，myBroadcast是自定义的绑定名称，in代表消费者，0是固定写法
          destination: my-broadcast-topic  # 对应的真实的 RabbitMQ Exchange

        # 分组消息
        myGroup-in-0: # 生产者绑定名称
          destination: my-group-topic  # 对应的真实的 RabbitMQ Exchange
          group: my-group-1