server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/hjhdaybreak/cloud-config3344.git
          #占位符
          search-paths:
            - cloud-config
          default-label: master
  rabbitmq:
    host: 192.168.8.129
    port: 5672
    username: guest
    password: guest


eureka:
  client:
    # 表示是否将自己注册到Eureka Server
    register-with-eureka: true
    # 示是否从Eureka Server获取注册的服务信息
    fetch-registry: true
    # Eureka Server地址
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
  instance:
    instance-id: cloud-config-center3344
    prefer-ip-address: true

